import Link from "next/link";
import { mockCampaigns, mockSubscribers, mockTags } from "../../../lib/newsletter/mockData";
import { formatDate, PageHeader, StatCard, StatusBadge } from "../../components/newsletter/AdminUi";

export default function NewsletterDashboard() {
  const active = mockSubscribers.filter((item) => item.status === "active").length;
  const unsubscribed = mockSubscribers.filter((item) => item.status === "unsubscribed").length;
  return <div className="mx-auto max-w-7xl"><PageHeader title="ダッシュボード" description="読者とキャンペーンの状況を確認できます。表示内容はPhase 1用の仮データです。" action={{ label: "キャンペーンを作成", href: "/admin/newsletter/campaigns/new" }} />
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="総読者数" value={mockSubscribers.length} /><StatCard label="配信中読者" value={active} /><StatCard label="配信停止読者" value={unsubscribed} note="配信対象から必ず除外" /><StatCard label="タグ数" value={mockTags.length} /><StatCard label="キャンペーン数" value={mockCampaigns.length} /></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-bold">最近の登録者</h2><Link href="/admin/newsletter/subscribers" className="text-sm font-semibold text-blue-700">すべて見る</Link></div><div className="divide-y divide-slate-100">{mockSubscribers.slice(0, 4).map((sub) => <div key={sub.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate text-sm font-semibold">{sub.name || "氏名未登録"}</p><p className="truncate text-xs text-slate-500">{sub.email}</p></div><div className="text-right"><StatusBadge status={sub.status} /><p className="mt-1 text-xs text-slate-500">{formatDate(sub.createdAt)}</p></div></div>)}</div></section>
      <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-bold">最近のキャンペーン</h2><Link href="/admin/newsletter/campaigns" className="text-sm font-semibold text-blue-700">すべて見る</Link></div><div className="divide-y divide-slate-100">{mockCampaigns.map((campaign) => <div key={campaign.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate text-sm font-semibold">{campaign.name}</p><p className="truncate text-xs text-slate-500">{campaign.subject}</p></div><div className="text-right"><StatusBadge status={campaign.status} /><p className="mt-1 text-xs text-slate-500">{formatDate(campaign.createdAt)}</p></div></div>)}</div></section></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3">{[["読者を管理", "/admin/newsletter/subscribers"], ["タグを管理", "/admin/newsletter/tags"], ["CSVを取り込む", "/admin/newsletter/import"]].map(([label, href]) => <Link key={href} href={href} className="rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold shadow-sm transition hover:border-blue-300 hover:text-blue-700">{label} →</Link>)}</div>
  </div>;
}
