"use client";

import { mockTags } from "../../../../../lib/newsletter/mockData";
import { PageHeader } from "../../../../components/newsletter/AdminUi";

export default function NewCampaignPage() {
  const inputClass = "mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
  return <div className="mx-auto max-w-4xl"><PageHeader title="キャンペーン作成" description="メールの内容と配信対象を準備します。Phase 1では入力内容を保存・送信しません。" /><form className="mt-6 space-y-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm" onSubmit={(event) => event.preventDefault()}><div><label htmlFor="campaign-name" className="text-sm font-semibold">キャンペーン名</label><input id="campaign-name" className={inputClass} placeholder="例：7月のHitoriBIZニュース" /></div><div><label htmlFor="subject" className="text-sm font-semibold">メール件名</label><input id="subject" className={inputClass} placeholder="受信トレイに表示する件名" /></div><div><label htmlFor="preview" className="text-sm font-semibold">プレビュー文</label><input id="preview" className={inputClass} placeholder="件名の横に表示される短い説明" /></div><div><label htmlFor="body" className="text-sm font-semibold">本文</label><textarea id="body" rows={12} className={inputClass} placeholder="メール本文を入力" /></div><fieldset><legend className="text-sm font-semibold">対象タグ</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{mockTags.map((tag) => <label key={tag.id} className="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><span className="flex items-center gap-3"><input type="checkbox" className="h-4 w-4 rounded text-blue-600" />{tag.name}</span><span className="text-xs text-slate-500">{tag.subscriberCount}名</span></label>)}</div></fieldset><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="test-email" className="text-sm font-semibold">テスト送信先</label><input id="test-email" type="email" className={inputClass} placeholder="test@example.com" /></div><div><label htmlFor="scheduled-at" className="text-sm font-semibold">配信予定日時</label><input id="scheduled-at" type="datetime-local" className={inputClass} /></div></div><div className="flex flex-wrap gap-3 border-t border-slate-200 pt-6"><button type="button" disabled className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white opacity-60">下書き保存（Phase 2）</button><button type="button" disabled className="rounded-lg border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-700 opacity-60">テスト送信（Phase 3）</button><button type="button" disabled className="rounded-lg border border-rose-300 px-5 py-2.5 text-sm font-semibold text-rose-700 opacity-60">本配信（Phase 4）</button></div></form></div>;
}
