import Foundation

enum L10n {
    static let appName = "String Tuner"
    static let ready = "Ready"
    static let listening = "Listening..."
    static let holdingTone = "Holding tone"
    static let pitchDetected = "Pitch detected"
    static let noInput = "No input detected"
    static let microphoneOff = "Microphone access is off"
    static let microphoneUnavailable = "Microphone permission is unavailable"
    static let requestingMicrophone = "Requesting microphone access"
    static let microphoneFailed = "Could not start microphone"
    static let microphoneSetupFailed = "Audio session setup failed"
    static let microphoneRequired = "Microphone access is required"
    static let microphoneHelp = "Open Settings and allow microphone access for String Tuner, then return and tap Listen."
    static let listen = "Listen"
    static let stop = "Stop"
    static let tone = "Tone"
    static let stopTone = "Stop Tone"
    static let target = "Target"
    static let detected = "Detected"
    static let inTune = "IN TUNE"
    static let tooLow = "Too low — tune up"
    static let tooHigh = "Too high — tune down"
    static let playSteady = "Play a steady open string"
    static let stable = "Stable tone"
    static let micInput = "Mic Input"
    static let setup = "Tuning Setup"
    static let instrument = "Instrument"
    static let openString = "Open String"
    static let a4Reference = "A4 Reference"
    static let privacy = "Audio is analyzed only on this device. It is never recorded, stored, or uploaded."
    static let toneStopsMic = "Playing a reference tone stops microphone listening."
}
